import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/globals.css";
import I18nProvider from "@/components/I18nProvider";
import Navbar from "@/components/Navbar"; // ✅ no dynamic here

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Welcome!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <I18nProvider>
          <Navbar /> {/* ✅ directly imported client component */}
          <main className="max-w-5xl mx-auto p-4 pt-16">{children}</main>
        </I18nProvider>
      </body>
    </html>
  );
}
